# wrangler.toml
name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-15"

kv_namespaces = [
    { binding = "KV_BINDING", id = "${KV_NAMESPACE_ID}" }
]


[assets]
directory = "./dist"
binding = "ASSETS"


[observability.logs]
enabled = true
